spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: "123"
    type: com.alibaba.druid.pool.DruidDataSource

  dubbo:
    application: #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      name: Provide
    registry: #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://127.0.0.1:2181
    protocol: #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
      name: dubbo
      port: 20880
    scan: com.dubboProvide.dubboProvide.service  #服务暴露与发现消费所在的package


server:
  port: 8086
