---
--- Generated by Luanalysis
--- Created by z30032142.
--- DateTime: 2022/11/23 14:12
---
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]
local nowTimeS = tonumber(ARGV[4])

local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'voucher:order:' .. voucherId

---判断库存是否充足，取出stock，判断是否大于0
---
if (tonumber(redis.call('HGET',stockKey,'num'))<=0) then
    -- 库存不足返回1
    return 1
end


if(tonumber(redis.call('HGET',stockKey,'startTime'))>nowTimeS) then
    -- 活动还未开始
    return 3
end

if(tonumber(redis.call('HGET',stockKey,'endTime'))<nowTimeS) then
    -- 活动已经结束
    return 4
end

if (tonumber(redis.call('SISMEMBER', orderKey,userId))==1)then
    -- 重复下单,返回2
    return 2
end
-- 资格判断没问题
-- 扣除库存【此处在redis中扣除就行】
redis.call('HINCRBY',stockKey,'num',-1) -- 利用自增方法，自增一个负数实现减一

-- 下单添加用户
redis.call('SADD',orderKey,userId) -- 向set value 中添加成员
-- 下单添加消息队列消息 XADD stream.orders * k1 v1 k2 v2 ...
redis.call('XADD','stream.orders', '*', 'userId',userId,'voucherId',voucherId,'id',orderId )

return 0